# Generated by Django 4.0.4 on 2022-05-06 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_alter_userrole_role_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('canceled', 'Canceled'), ('pending', 'Pending')], max_length=15, verbose_name='Request status')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField(default=0, verbose_name='Total area to be cleaned')),
                ('address', models.TimeField(verbose_name='User`s address')),
                ('total_cost', models.FloatField(verbose_name='Final cost of the service')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requeststatus')),
            ],
        ),
    ]
