# Generated by Django 4.0.4 on 2022-05-07 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_requeststatus_status_review'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 22, 49, 39, 992929), verbose_name='Time of creation'),
        ),
    ]
