# Generated by Django 3.2.13 on 2022-06-02 17:10

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_service_company_alter_requeststatus_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='company',
        ),
        migrations.AddField(
            model_name='user',
            name='address_details',
            field=models.CharField(default=1, max_length=256, verbose_name='District, house, apartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=1, max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=1, max_length=50, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(null=True, to='core.Service'),
        ),
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=15, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 22, 10, 45, 210925), verbose_name='Time of creation'),
        ),
    ]
