# Generated by Django 3.2.13 on 2022-06-03 19:08

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220603_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='address',
        ),
        migrations.AddField(
            model_name='notification',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='Request was accepted'),
        ),
        migrations.AddField(
            model_name='request',
            name='address_details',
            field=models.CharField(default=1, max_length=250, verbose_name='District, street, house, apartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.CharField(default=1, max_length=100, verbose_name='City of request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='country',
            field=models.CharField(default=1, max_length=100, verbose_name='Country of request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 0, 8, 2, 91197), verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Star-rating'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(to='core.Service'),
        ),
    ]
