# Generated by Django 3.2.13 on 2022-06-04 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220604_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='accept',
            new_name='accepted',
        ),
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'Pending'), ('completed', 'Completed')], max_length=15, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 20, 19, 56, 226053), verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('company', 'Company'), ('customer', 'Customer')], max_length=15, verbose_name='User`s role'),
        ),
    ]
