# Generated by Django 3.2.13 on 2022-06-04 18:29

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220604_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='services_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'Pending'), ('completed', 'Completed'), ('accepted', 'Accepted')], max_length=15, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 23, 29, 24, 41738), verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Star-rating'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('company', 'Company')], max_length=15, verbose_name='User`s role'),
        ),
    ]
