# Generated by Django 3.2.13 on 2022-06-04 18:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220604_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='profile_pic',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('pending', 'Pending')], max_length=15, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 23, 32, 59, 192522), verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('company', 'Company'), ('customer', 'Customer')], max_length=15, verbose_name='User`s role'),
        ),
    ]
