# Generated by Django 3.2.13 on 2022-06-05 15:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220605_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accepted',
            field=models.BooleanField(default=True, verbose_name='Is order accepted by user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Request_order', to='core.request'),
        ),
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('completed', 'Completed'), ('accepted', 'Accepted'), ('pending', 'Pending')], max_length=15, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 20, 20, 53, 1196), verbose_name='Time of creation'),
        ),
    ]
