# Generated by Django 3.2.13 on 2022-06-06 16:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220605_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='max_hour_price',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Maximum affordable price per hour'),
        ),
        migrations.AddField(
            model_name='request',
            name='min_rating_needed',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Minimum required company`s rating'),
        ),
        migrations.AddField(
            model_name='user',
            name='users_rated',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of user rated'),
        ),
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('accepted', 'Accepted'), ('canceled', 'Canceled'), ('pending', 'Pending')], max_length=15, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 21, 5, 50, 221688), verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(to='core.Service', verbose_name='Company`s services'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('company', 'Company')], max_length=15, verbose_name='User`s role'),
        ),
    ]
