# Generated by Django 3.2.13 on 2022-06-06 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220606_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('completed', 'Completed')], max_length=15, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 22, 17, 26, 747275), verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Service name'),
        ),
    ]
