# Generated by Django 3.2.13 on 2022-06-07 17:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220607_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 22, 22, 43, 555662), verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hour_cost',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost per working hour'),
        ),
    ]
