# Generated by Django 3.2.13 on 2022-06-10 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220610_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='hours_required',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hour_cost',
        ),
        migrations.AddField(
            model_name='user',
            name='meter_cost',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost per square meter'),
        ),
    ]
