# Generated by Django 3.2.13 on 2022-06-10 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20220610_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='max_hour_price',
        ),
        migrations.AddField(
            model_name='request',
            name='max_meter_cost',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Maximum affordable price per meter'),
        ),
    ]
