# Generated by Django 4.0.4 on 2022-05-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('company', 'Company')], max_length=15, verbose_name='User`s role')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='User`s name')),
                ('email', models.EmailField(max_length=254, verbose_name='User`s email')),
                ('phone', models.CharField(max_length=100, verbose_name='User`s phone')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userrole')),
            ],
        ),
    ]
