# Generated by Django 4.0.4 on 2022-05-06 10:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_requeststatus_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('completed', 'Completed')], max_length=15, verbose_name='Request status'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TimeField(verbose_name='Customer`s feedback')),
                ('rate', models.PositiveIntegerField(default=0, verbose_name='Star-rating')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 5, 6, 15, 22, 34, 727057), verbose_name='Time of creation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.request')),
            ],
        ),
    ]
