# Generated by Django 4.0.4 on 2022-05-01 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name of the service')),
                ('service_image', models.ImageField(upload_to='images/service_images/', verbose_name='Image of a service')),
                ('price', models.FloatField(verbose_name='Price of the service')),
                ('deadline', models.IntegerField(verbose_name='Required hours to complete service')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
    ]
