# Generated by Django 4.0.4 on 2022-05-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Company name')),
                ('city', models.CharField(max_length=100, verbose_name='Company location city')),
                ('rating', models.FloatField(default=0, verbose_name='Rating of the company')),
                ('order_number', models.IntegerField(default=0, verbose_name='Number of completed orders')),
                ('phone', models.CharField(max_length=100, unique=True, verbose_name='Company`s phone number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Company`s email')),
                ('logo', models.ImageField(upload_to='images/logos/', verbose_name='Logo of the company')),
            ],
            options={
                'verbose_name_plural': 'Company profiles',
            },
        ),
    ]
