# Generated by Django 4.0.4 on 2022-05-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fullname', models.CharField(max_length=256, verbose_name='User`s fullname')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User`s nickname')),
                ('age', models.IntegerField(verbose_name='User`s age')),
                ('phone', models.CharField(max_length=100, verbose_name='User`s phone number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='User`s email')),
                ('city', models.CharField(max_length=256, verbose_name='User`s city')),
                ('profile_image', models.ImageField(upload_to='images/profile_images/', verbose_name='Profile image')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
